const teamData = [
  {
    id: 1,
    firstName: "Mario",
    lastName: "Speedwagon",
    role: "Project architect",
    email: "marioSpeedwagon@gmail.com",
    image: "https://images.dog.ceo/breeds/hound-blood/n02088466_9576.jpg",
  },
  {
    id: 2,
    firstName: "Petey",
    lastName: "Cruiser",
    role: "Project manager",
    email: "peteyCruiser@gmail.com",
    image: "https://images.dog.ceo/breeds/hound-english/n02089973_3307.jpg",
  },
  {
    id: 3,
    firstName: "Anna",
    lastName: "Sthesia",
    role: "UI/UX designer",
    email: "annaSthesia@gmail.com",
    image: "https://images.dog.ceo/breeds/hound-afghan/n02088094_8063.jpg",
  },
  {
    id: 4,
    firstName: "Paul",
    lastName: "Molive",
    role: "UI/UX designer",
    email: "paulMolive@gmail.com",
    image: "https://images.dog.ceo/breeds/hound-walker/n02089867_1882.jpg",
  },
  {
    id: 5,
    firstName: "Anna",
    lastName: "Mull",
    role: "Web developer",
    email: "annaMull@gmail.com",
    image: "https://images.dog.ceo/breeds/hound-blood/n02088466_6834.jpg",
  },
  {
    id: 6,
    firstName: "Gail",
    lastName: "Forcewind",
    role: "Web developer",
    email: "gailForcewind@gmail.com",
    image: "https://images.dog.ceo/breeds/hound-basset/n02088238_11281.jpg",
  },
  {
    id: 7,
    firstName: "Bob",
    lastName: "Frapples",
    role: "Web developer",
    email: "bobFrapples@gmail.com",
    image: "https://images.dog.ceo/breeds/hound-english/n02089973_3119.jpg",
  },
];
export default teamData;
