const teamData = [
  {
    id: 1,
    firstName: "Mario",
    lastName: "Speedwagon",
    role: "Project architect",
    email: "marioSpeedwagon@gmail.com",
    image: "https://loremflickr.com/320/240",
  },
  {
    id: 2,
    firstName: "Petey",
    lastName: "Cruiser",
    role: "Project manager",
    email: "peteyCruiser@gmail.com",
    image: "https://loremflickr.com/320/240",
  },
  {
    id: 3,
    firstName: "Anna",
    lastName: "Sthesia",
    role: "UI/UX designer",
    email: "annaSthesia@gmail.com",
    image: "https://loremflickr.com/320/240",
  },
  {
    id: 4,
    firstName: "Paul",
    lastName: "Molive",
    role: "UI/UX designer",
    email: "paulMolive@gmail.com",
    image: "https://loremflickr.com/320/240",
  },
  {
    id: 5,
    firstName: "Anna",
    lastName: "Mull",
    role: "Web developer",
    email: "annaMull@gmail.com",
    image: "https://loremflickr.com/320/240",
  },
  {
    id: 6,
    firstName: "Gail",
    lastName: "Forcewind",
    role: "Web developer",
    email: "gailForcewind@gmail.com",
    image: "https://loremflickr.com/320/240",
  },
  {
    id: 7,
    firstName: "Bob",
    lastName: "Frapples",
    role: "Web developer",
    email: "bobFrapples@gmail.com",
    image: "https://loremflickr.com/320/240",
  },
];
export default teamData;
